# This is a SecretProviderClass example using user-assigned identity to access your key vault
# Service Connector sets up the Azure resource connection, users only need create the SecretProviderClass and workload resources
# For the variables to fill in, you may get their values from Service Connector Azure Portal


apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sc-demo-keyvault-csi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                        # Set to true for using managed identity
    userAssignedIdentityID: <AZURE_KEYVAULT_CLIENTID>   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: <AZURE_KEYVAULT_NAME>                 # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: <KEYVAULT_SECRET_NAME>            # keyvault secret name
          objectType: secret
    tenantId: <AZURE_KEYVAULT_TENANTID>                 # The tenant ID of the key vault